### ISSUE TITLE
Setting threshA/C = 0 in dm.plot_enrichment_profile() function plots fluctuations instead of flat lines  

### ISSUE THREAD

**Issue by MichalRozenwald** [streetslab/dimelo#38]
When setting the `threshA` and  `threshC` parameters to 0 in the `dm.plot_enrichment_profile()` function from the
the dimelo package using the dimilo test ctcf demo data from github in the rolling avg plots we get lines that are fluctuating 
([CTCF_demo_A+CG_sm_rolling_avg.pdf](https://drive.google.com/file/d/19pn0zeNbx_b0TPxL5QTfUdQ1GTezNWDg/view?usp=sharing )). 
The expectation was to see flat horizontal y-lines corresponding to the fractions equal to 1 instead of fluctuations as all the regions are supposed to be considered methylated when setting the thresholds to be equal to zero. 
What could be the reason for that?

Here is the code:
```
import dimelo as dm
bam = "/content/dimelo/dimelo/test/data/ctcf_demo.sorted.bam"
sampleName = "CTCF_demo"
outDir = "/content/dimelo_ctcf_test_out"
bedPeak = "/content/dimelo/dimelo/test/data/ctcf_demo_peak.bed"
bedNotPeak = "/content/dimelo/dimelo/test/data/ctcf_demo_not_peak.bed"

dm.plot_enrichment_profile(bam, sampleName,  bedPeak,   "A+CG",
    outDir + "/plot_enrichment_profile_threshAC0",
    threshA=0, threshC=0)
```

And here is a Google Colab Notebook installing dimelo package and reproducing these results and figures:
https://colab.research.google.com/drive/1ajMwrk98OVuT176DafGKxEuaH7U55-OV?usp=sharing

**Comment by OberonDixon** [comment]
My guess here is that this is because, for a single region, the behavior used to be that the rolling average (default size 25 or something) would get zeros for places with no valid or modified bases in the pileup. This is now changed with the modkit_parsing_beta branch, with the implementation of JIRA issue DM-1 with [commit](https://github.com/streetslab/dimelo/commit/9a5d2a40fc2d6fbac6f21c259f57205fcc30d4ab).

However, we also do not *allow* thresholds of zero with this version; `dimelo.parse_bam.pileup` and `dimelo_parse_bam.extract` will raise errors. A threshold of zero is a meaningless analysis as it will by definition be 100% everywhere where the motif is present.
